# Use uma imagem base do MySQL
FROM mysql:8

# Defina variáveis de ambiente para inicializar o banco de dados
ENV MYSQL_ROOT_PASSWORD=123
ENV MYSQL_DATABASE=mysql
ENV MYSQL_USER=wmeneghini
ENV MYSQL_PASSWORD=123

# Copie arquivos SQL de inicialização (se necessário)
# COPY init.sql /docker-entrypoint-initdb.d/
